#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.0.{build}

# Do not build on tags
skip_tags: false

# Start builds on tags only
skip_non_tags: false

# Skipping commits affecting specific files
skip_commits:
  files:
  - '**\AssemblyInfo.*'
  - 'CHANGELOG.md'

# 
pull_requests:
  do_not_increment_build_number: true
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $env:RocketBot2_Version = "$($env:APPVEYOR_REPO_TAG_NAME.Replace('v', ''))";
    }
    else
    {
        $env:RocketBot2_Version = "$($env:APPVEYOR_BUILD_VERSION)";
    }

# clone directory
clone_folder: c:\projects\rocketbot2

# fetch repository as zip archive
shallow_clone: false

# set clone depth
#clone_depth:  5                     # clone entire repository history if not defined

# environment variables
environment:
  auth_token:
    secure: i2lM8pWf+r7jq8FkcoqzcdCcol38VFcgEyEKDdpD+qY=
  github_user:
    secure: 49U9BXmCbVT2hnh4fE4vHQ==   
  github_email:
    secure: hpBRtDQpNVSg3mr0m8jBDv7lEhz6npf8eCC4Gtjzukc=
  priv_key::
    secure: nXveAwrHPoEt1bEyd/M9nihYBR0E2+SC/4GfmzYczn6Xlq7Ev5SYFH2o1aaJ443GrG6vLxJ0vbuq0UTVnpXndU3kpmLunWE9utQanQ8T60dx5Kp4nkd8P/1+ZBcUoUCe4xUKiR5u/y7iNJlJ+Gd0BEHZ/MRvVxZckn4XE3aNe+0WhrVoAWR/bgJgFBGLxeYYGevYNkjT7fMBfc7gl4JnHD2eErgoDHj3ilYiH5hMbH/Vbu4WPoxmbC5lM16rbXd/lMv6EuNBb6kkaX3YSyvofYwdHP/gbSdzoCKt/l7KEAitxmQSS8XvoQj+0xhhugV4DnQyPGIHkP5TNDqz6CUdRKVFIcjTMFzqVi9C2db4Kmus9B352B/edhOFVgKhRRshVHasElxOSyO5FX3agRguMRVRxMNGoZmzvQSx0/AUyOVk/e0Sg7wxMuZnNK0RusMzVJ4ff/rwGJYvKr/9lDkhQrMzrYAPUuc12Lm5r/OanuvfS4j9Eu7qmzicCJb/G2WE7AYGMxh19H0wRQSST+ymerxy0cy4d8t7oroGZVJmVStzr0BQtwbM4jNg+26t9VJPClv538DxJoXdsdKf3ETsEyQCNwBiHjeRuKWn1Am2+zZHB9CMQEzpebHoWsa1LOIcQhPBjBhp8RYpCGGsiAaiNS/PoSgh/Hhd1Jhf+sBVvoSJ+Bdi1z8ofTqQZ3sdny3QR9kQw7RXUajPWdjLpevKnI1L5s0OS5yEFldWzUfAf8miEpqzILO/gaAsg/pIfyh/HhbgUV4nhvWM0MOFdmKV7fHRfC/Qfs3/l7LvsO5nKmAqB1PT02eBpVaMAP9SSHxIpJZYvQx4C9gR4RA63C9E8yJ3ku5oMwWB/wumSqoZuPLX5ZvwipQF0EIdwt2OFjtt2hzDDmuhyrVgTEXMWEp5S/PfmxbdzIyFg4yRBQF3ebschK/77EMMzNhAbMncLx1DfjoIzgxPnJ9uxotmwpaKFhT0sO4FMrLfg97N2dqF8ZjSxg/P7AZXm6TIRAw9PSXNkkIx/fa9KAVof6rV3+s5KPKnreF3O9S7lnkCF1nhu415vtCbG/hBQgheX0BDBpgSl6xhS0Uf5kBUD4d9Oy9iP1jckAEDw7SmFnIAQWqRigEbS2xS4SyyTgZpluPmAWJ84SAlaAkM4MMKcdVqPN/WQHYNRDAHq/lHHKXvpDYMKUWdZr/dLLV8tbGBFjZJzCXDykGQBV1AYZ8uF7wC3cTEQEqstoW618+eJCmidNp7j6rOxb74z9ckamzTQRU26AaiKnpoq6jrPMn5HHONXQklZvxoNMg7w+RbXxQUrd0uXhT7ozCKJz8+wTQ/XmVpgjluQLdlRLW8z9i5mDwpqTEK/MA4p6PoI1oQng3v7s6sCmPvAWGKVOc8j7NB10sGaAGgswdbNKB/eoTI8BnZg9U6lV7gso5szMj1xKH0RFENuhP5/Ditz0w9B7lpQxppqkr/+ue76ERLcjtnGBRHqTyj7hxPDOxWU5dA81KVoqG0afEKzqfrds8J0+/iD0Vy9hfEBytT8VHEmLMqXX+hnSWq6j1nO1jqw5G5YWyx1TrphOUYqcFan7mthz5Ivdv+uhVxzITQ1ek2b1w0VRwUr1ziDw/5fT2sUN07VuZMoJSAL4MEUknBYnHSOVsNPot+ZYzu8gRg7gsHkZzNbqwprUlHNSUilEuB/B9AhOOVmLHFOsA0L8c+aJlSHa4zZEnoT6ElIAOeV6zlzvSrw2LhRsBWtwMOSkwvg2jh7pb1yFTrBvgl32ArOkn8RdurHoAX2H2R1SqtPa1iZkeyI9OZwZC9WK3J8CS4VkJBghnjNUah9Uze4K/O177nD8KNUWFAqgKAvOvS4ZAVfs8r6vwEa5usRznrpXkbjGzJ3OcvbTdjugZCuevrWCJGEcgbObvrHZtpIp5JYsZknoi+voJjp1+yu3wVz9wtOhpVEzycW54P4jNovdUr9NiznyGL4NAAoSTYDgVx2W6/xlAmrjALLoxjuvctvVEJkMMES1Hfeer+iwMUzfQX2a42sHuCJPKrXktoEHvKiVs1BF/aJYc6BsbjZufGlqRkvdyKNEK0G7OoUfZAxnCrFCbse90uUFPqVWHy/zJovMSTXBKB8aoXmUz/fVazXRRgMSQaACxBaxWSdzVG2xSayf1EpxEatVgUvty8zG0i6VYnnKimnsDuwnU+1+WRc6rv+1Kh0LhttOZ/S2czm7XJgaGQyj766ASmaySO

# build cache to preserve files/folders between builds
#cache:
#  - packages -> **\packages.config  # preserve packages directory in the root of build folder but will reset it if packages.config is modified
#  - '%LocalAppData%\NuGet\Cache'

# scripts that run after cloning repository
install:
- git submodule update --init --recursive

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(RocketBot2_Version)'
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: '$(APPVEYOR_REPO_TAG_NAME)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - nuget restore

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:
- ps: >-
    Remove-Item "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)" -Recurse -ErrorAction Ignore;
    New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)";
    New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)";
    if ($env:PLATFORM -eq "x86")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\RocketBot2\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\RocketBot2" -Force;
    }  
    elseif ($env:PLATFORM -eq "x64")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\RocketBot2\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\RocketBot2" -Force;
    }
    elseif ($env:PLATFORM -eq "Any CPU")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\RocketBot2\bin\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\RocketBot2" -Force;
    }
        

# to run your custom scripts instead of automatic MSBuild
build_script:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: '\$(PLATFORM)\$(CONFIGURATION)\RocketBot2'
    name: Release

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

  # Deploy to GitHub Releases
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '[README.md](https://github.com/TheUnnamedOrganisation/RocketBot/blob/master/README.md)'
    release: RocketBot2 $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(auth_token)
    artifact: Release
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

# scripts to run before deployment
before_deploy:
- ps: >-
    $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n";
    $fileContent += $env:priv_key.Replace(' ', "`n");
    $fileContent += "`n-----END RSA PRIVATE KEY-----`n";
    Set-Content "$env:USERPROFILE\.ssh\id_rsa" "$($fileContent)";
    Set-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n";

- git config --global credential.helper store
- git config --global user.email "%github_email%"
- git config --global user.name "%github_user%"
- git checkout -b Appveyor "%APPVEYOR_REPO_BRANCH%"
- SET PATH=C:\Ruby23\bin;%PATH%
- git add "RocketBot2/Properties/AssemblyInfo.cs"
- git commit -m "%APPVEYOR_REPO_TAG_NAME%"
- git checkout "%APPVEYOR_REPO_BRANCH%"
- git merge Appveyor
- git branch -d Appveyor
- git pull "origin" "%APPVEYOR_REPO_BRANCH%"
- git push "origin" "%APPVEYOR_REPO_BRANCH%"

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:

# on build failure
on_failure:

# after build failure or success
on_finish:
