version: 0.0.0.{build}
configuration: Release RocketBot2
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(RocketBot2_Version)
  assembly_file_version: 1.0.0.0
  assembly_informational_version: $(APPVEYOR_REPO_TAG_NAME)
install:
- ps: '- git submodule update --init --recursive'
before_build:
- ps: '- nuget restore'
build:
  project: RocketBot.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: "Remove-Item \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\" -Recurse -ErrorAction Ignore;\n    New-Item -ItemType Directory -Force -Path \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\";\n    New-Item -ItemType Directory -Force -Path \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\\$($env:CONFIGURATION)\";\n    if ($env:PLATFORM -eq \"x86\")\n    {\n        Move-Item -Path \"$($env:APPVEYOR_BUILD_FOLDER)\\RocketBot2\\bin\\$($env:PLATFORM)\\$($env:CONFIGURATION)\" -Destination \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\\$($env:CONFIGURATION)\\RocketBot2\" -Force;\n    }  \n    elseif ($env:PLATFORM -eq \"x64\")\n    {\n        Move-Item -Path \"$($env:APPVEYOR_BUILD_FOLDER)\\RocketBot2\\bin\\$($env:PLATFORM)\\$($env:CONFIGURATION)\" -Destination \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\\$($env:CONFIGURATION)\\RocketBot2\" -Force;\n    }\n    elseif ($env:PLATFORM -eq \"Any CPU\")\n    {\n        Move-Item -Path \"$($env:APPVEYOR_BUILD_FOLDER)\\RocketBot2\\bin\\$($env:CONFIGURATION)\" -Destination \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:PLATFORM)\\$($env:CONFIGURATION)\\RocketBot2\" -Force;\n    }"
artifacts:
- path: '\$(PLATFORM)\$(CONFIGURATION)\RocketBot2'
  name: Release
before_deploy:
- ps: >-
    $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n";
        $fileContent += $env:priv_key.Replace(' ', "`n");
        $fileContent += "`n-----END RSA PRIVATE KEY-----`n";
        Set-Content "$env:USERPROFILE\.ssh\id_rsa" "$($fileContent)";
        Set-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n";

    - git config --global credential.helper store

    - git config --global user.email "%github_email%"

    - git config --global user.name "%github_user%"

    - git checkout -b Appveyor "%APPVEYOR_REPO_BRANCH%"

    - SET PATH=C:\Ruby23\bin;%PATH%

    - git add "RocketBot2/Properties/AssemblyInfo.cs"

    - git commit -m "%APPVEYOR_REPO_TAG_NAME%"

    - git checkout "%APPVEYOR_REPO_BRANCH%"

    - git merge Appveyor

    - git branch -d Appveyor

    - git pull "origin" "%APPVEYOR_REPO_BRANCH%"

    - git push "origin" "%APPVEYOR_REPO_BRANCH%"
deploy:
- provider: GitHub
  auth_token:
    secure: i2lM8pWf+r7jq8FkcoqzcdCcol38VFcgEyEKDdpD+qY=
  artifact: Release
  force_update: true